# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 940444bfc8001d514fcfddb98bb512b888c9635a248260093b5d8ae6dbed27f198248d5c6f687125a17a7a0c2c04a1b9e8407f196753ce20727d357d0ae39c4c

test:
  secret_key_base: 8887f4c23d7f7f0a8a8e76099c728edc864d976db9b3048f25e2d730f058cce277a2b1e38e7447c35889dcf294e0099cf1f15611edb80256a41d5f3dfc8a5693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
